version: "3"
networks:
  net:
    driver: bridge
services:
  elasticsearch:
    image: pycontribs/centos:7
    container_name: elasticsearch
    ports:
      - "9200:9200"
    networks:
      - net
    tty: true
  kibana:
    image: pycontribs/centos:7
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - net
    tty: true





 