---
all:
  hosts:
    app-instance:
      ansible_host: 62.84.116.196
      local_ip: 10.128.0.17
    el-instance:
      ansible_host: 62.84.117.55
      local_ip: 10.128.0.31
    k-instance:
      ansible_host: 62.84.118.55
      local_ip: 10.128.0.10
  vars:
    ansible_connection: ssh
    ansible_user: centos

application:
  hosts:
    app-instance:
elasticsearch:
  hosts:
    el-instance:
kibana:
  hosts:
    k-instance:
