FROM ubuntu:20.04
env DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install --no-install-recommends -y \ 
    python3.9 python3.9-dev python3.9-venv python3-pip && \
    apt-get clean && rm -rf /var/lib/apt/lists/
CMD ["/bin/bash"]